/*----- PROTECTED REGION ID(PowerPMACAxesStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        PowerPMACAxesStateMachine.cpp
//
// description : C++ source for the �name� and its alowed
//               methods for commands and attributes
//
// project :     Power PMAC Axes.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <PowerPMACAxes.h>
#include <PowerPMACAxesClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * PowerPMACAxes states description:
 *
 * ON :	PowerPMACAxes device server is connected to the Power PMAC and ready to send command and read attributes. 
 * OFF :	The device server is not connected to the Power PMAC. 
 * UNKNOWN :	Unknown state 
 */

namespace PowerPMACAxes_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1CurrentPositionState_allowed()
 *	Description : Execution allowed for Axis1CurrentPosition attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1CurrentPosition_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1CurrentPositionStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1CurrentPositionStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Motor1StatusState_allowed()
 *	Description : Execution allowed for Motor1Status attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Motor1Status_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Motor1StatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Motor1StatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1PoweredState_allowed()
 *	Description : Execution allowed for Axis1Powered attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1Powered_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1PoweredStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1PoweredStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_CS1StatusState_allowed()
 *	Description : Execution allowed for CS1Status attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_CS1Status_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_CS1StatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_CS1StatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1DeadBandState_allowed()
 *	Description : Execution allowed for Axis1DeadBand attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1DeadBand_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::OFF	|| 
			get_state() == Tango::UNKNOWN)
		{
		
	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1DeadBandStateAllowed_WRITE) ENABLED START -----*/
        if (
            get_state() == Tango::OFF	|| 
            get_state() == Tango::UNKNOWN)
        {
            return false;
        }
	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1DeadBandStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1DeadBandStateAllowed_READ) ENABLED START -----*/
        if (
            get_state() == Tango::OFF	|| 
            get_state() == Tango::UNKNOWN)
        {
            return false;
        }
	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1DeadBandStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1SpeedState_allowed()
 *	Description : Execution allowed for Axis1Speed attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1Speed_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::OFF	|| 
			get_state() == Tango::UNKNOWN)
		{
		
	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1SpeedStateAllowed_WRITE) ENABLED START -----*/
        if (
            get_state() == Tango::OFF	|| 
            get_state() == Tango::UNKNOWN)
        {
            return false;
        }
	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1SpeedStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1SpeedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1SpeedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1AccelerationState_allowed()
 *	Description : Execution allowed for Axis1Acceleration attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1Acceleration_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::OFF	|| 
			get_state() == Tango::UNKNOWN)
		{
		
	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1AccelerationStateAllowed_WRITE) ENABLED START -----*/
    if (
            get_state() == Tango::OFF	|| 
            get_state() == Tango::UNKNOWN)
        {
            return false;
        }
	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1AccelerationStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1AccelerationStateAllowed_READ) ENABLED START -----*/
    {
        if (
            get_state() == Tango::OFF	|| 
            get_state() == Tango::UNKNOWN)
        {
            return false;
        }
    }
	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1AccelerationStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axes1to3PositionsState_allowed()
 *	Description : Execution allowed for Axes1to3Positions attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axes1to3Positions_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axes1to3PositionsStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axes1to3PositionsStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Motor1to3StatusState_allowed()
 *	Description : Execution allowed for Motor1to3Status attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Motor1to3Status_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Motor1to3StatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Motor1to3StatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_CS1to3StatusState_allowed()
 *	Description : Execution allowed for CS1to3Status attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_CS1to3Status_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_CS1to3StatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_CS1to3StatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axes1to3VelocitiesState_allowed()
 *	Description : Execution allowed for Axes1to3Velocities attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axes1to3Velocities_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axes1to3VelocitiesStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axes1to3VelocitiesStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1SoftwareLimitsState_allowed()
 *	Description : Execution allowed for Axis1SoftwareLimits attribute.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1SoftwareLimits_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::OFF	|| 
			get_state() == Tango::UNKNOWN)
		{
		
	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1SoftwareLimitsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1SoftwareLimitsStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(PowerPMACAxes::read_Axis1SoftwareLimitsStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::read_Axis1SoftwareLimitsStateAllowed_READ

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(PowerPMACAxes::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_AxisHomeState_allowed()
 *	Description : Execution allowed for AxisHome command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_AxisHome_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::AxisHomeStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::AxisHomeStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_AxisStopState_allowed()
 *	Description : Execution allowed for AxisStop command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_AxisStop_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::AxisStopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::AxisStopStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_AxisAbortState_allowed()
 *	Description : Execution allowed for AxisAbort command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_AxisAbort_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::AxisAbortStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::AxisAbortStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_AxisMovePositiveState_allowed()
 *	Description : Execution allowed for AxisMovePositive command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_AxisMovePositive_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::AxisMovePositiveStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::AxisMovePositiveStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_AxisMoveNegativeState_allowed()
 *	Description : Execution allowed for AxisMoveNegative command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_AxisMoveNegative_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::AxisMoveNegativeStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::AxisMoveNegativeStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1MoveAbsState_allowed()
 *	Description : Execution allowed for Axis1MoveAbs command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1MoveAbs_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1MoveAbsStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1MoveAbsStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1MoveRelState_allowed()
 *	Description : Execution allowed for Axis1MoveRel command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1MoveRel_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1MoveRelStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1MoveRelStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::is_Axis1DefinePositionState_allowed()
 *	Description : Execution allowed for Axis1DefinePosition command.
 */
//--------------------------------------------------------

bool PowerPMACAxes::is_Axis1DefinePosition_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(PowerPMACAxes::Axis1DefinePositionStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Axis1DefinePositionStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(PowerPMACAxes::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::are_dynamic_commands_allowed

}	// namespace PowerPMACAxes_ns
