/*----- PROTECTED REGION ID(PowerPMACAxesClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        PowerPMACAxesClass.cpp
//
// description : C++ source for the PowerPMACAxesClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     Power PMAC Axes.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PowerPMACAxesClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create PowerPMACAxesClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PowerPMACAxes_class(const char *name) {
		return PowerPMACAxes_ns::PowerPMACAxesClass::init(name);
	}
}


namespace PowerPMACAxes_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PowerPMACAxesClass *PowerPMACAxesClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::PowerPMACAxesClass(string &s)
 * description : 	constructor for the PowerPMACAxesClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PowerPMACAxesClass::PowerPMACAxesClass(string &s):DeviceClass(s)
{
	cout2 << "Entering PowerPMACAxesClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::constructor

	cout2 << "Leaving PowerPMACAxesClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::~PowerPMACAxesClass()
 * description : 	destructor for the PowerPMACAxesClass
 */
//--------------------------------------------------------
PowerPMACAxesClass::~PowerPMACAxesClass()
{
	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PowerPMACAxesClass *PowerPMACAxesClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PowerPMACAxesClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PowerPMACAxesClass *PowerPMACAxesClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		AxisHomeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AxisHomeClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AxisHomeClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis_home(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AxisStopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AxisStopClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AxisStopClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis_stop(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AxisAbortClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AxisAbortClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AxisAbortClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis_abort(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AxisMovePositiveClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AxisMovePositiveClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AxisMovePositiveClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis_move_positive(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AxisMoveNegativeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AxisMoveNegativeClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AxisMoveNegativeClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis_move_negative(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		Axis1MoveAbsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *Axis1MoveAbsClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "Axis1MoveAbsClass::execute(): arrived" << endl;

	Tango::DevDouble	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis1_move_abs(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		Axis1MoveRelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *Axis1MoveRelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "Axis1MoveRelClass::execute(): arrived" << endl;

	Tango::DevDouble	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis1_move_rel(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		Axis1DefinePositionClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *Axis1DefinePositionClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "Axis1DefinePositionClass::execute(): arrived" << endl;

	Tango::DevDouble	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACAxes *>(device))->axis1_define_position(argin));
	return new CORBA::Any();
}




//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACAxesClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACAxesClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACAxesClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void PowerPMACAxesClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void PowerPMACAxesClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties

	prop_name = "IpAddress";
	prop_desc = "IP Address of a Power PMAC";
	prop_def  = "192.168.0.48\n";
	vect_data.clear();
	vect_data.push_back("192.168.0.48");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Username";
	prop_desc = "Username for Power PMAC SSH connection";
	prop_def  = "root\n";
	vect_data.clear();
	vect_data.push_back("root");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Password";
	prop_desc = "Password for Power PMAC SSH connection";
	prop_def  = "deltatau\n";
	vect_data.clear();
	vect_data.push_back("deltatau");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PowerPMACAxesClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Power PMAC Axes");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Send axes command and read axes data from Power PMAC.");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("PowerPMACAxes");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void PowerPMACAxesClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PowerPMACAxes(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PowerPMACAxes *dev = static_cast<PowerPMACAxes *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void PowerPMACAxesClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::attribute_factory_before


	//	Attribute : Axis1CurrentPosition
	Axis1CurrentPositionAttrib	*axis1currentposition = new Axis1CurrentPositionAttrib();
	Tango::UserDefaultAttrProp	axis1currentposition_prop;
	//	description	not set for	Axis1CurrentPosition
	//	label	not set for	Axis1CurrentPosition
	//	unit	not set for	Axis1CurrentPosition
	//	standard_unit	not set for	Axis1CurrentPosition
	//	display_unit	not set for	Axis1CurrentPosition
	//	format	not set for	Axis1CurrentPosition
	//	max_value	not set for	Axis1CurrentPosition
	//	min_value	not set for	Axis1CurrentPosition
	//	max_alarm	not set for	Axis1CurrentPosition
	//	min_alarm	not set for	Axis1CurrentPosition
	//	max_warning	not set for	Axis1CurrentPosition
	//	min_warning	not set for	Axis1CurrentPosition
	//	delta_t	not set for	Axis1CurrentPosition
	//	delta_val	not set for	Axis1CurrentPosition
	axis1currentposition->set_default_properties(axis1currentposition_prop);
	//	Not Polled
	axis1currentposition->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1CurrentPosition does not fire change event
	//	Axis1CurrentPosition does not fire archive event
	//	Axis1CurrentPosition does not fire data_ready event
	att_list.push_back(axis1currentposition);

	//	Attribute : Motor1Status
	Motor1StatusAttrib	*motor1status = new Motor1StatusAttrib();
	Tango::UserDefaultAttrProp	motor1status_prop;
	//	description	not set for	Motor1Status
	//	label	not set for	Motor1Status
	//	unit	not set for	Motor1Status
	//	standard_unit	not set for	Motor1Status
	//	display_unit	not set for	Motor1Status
	//	format	not set for	Motor1Status
	//	max_value	not set for	Motor1Status
	//	min_value	not set for	Motor1Status
	//	max_alarm	not set for	Motor1Status
	//	min_alarm	not set for	Motor1Status
	//	max_warning	not set for	Motor1Status
	//	min_warning	not set for	Motor1Status
	//	delta_t	not set for	Motor1Status
	//	delta_val	not set for	Motor1Status
	motor1status->set_default_properties(motor1status_prop);
	//	Not Polled
	motor1status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Motor1Status does not fire change event
	//	Motor1Status does not fire archive event
	//	Motor1Status does not fire data_ready event
	att_list.push_back(motor1status);

	//	Attribute : Axis1Powered
	Axis1PoweredAttrib	*axis1powered = new Axis1PoweredAttrib();
	Tango::UserDefaultAttrProp	axis1powered_prop;
	//	description	not set for	Axis1Powered
	//	label	not set for	Axis1Powered
	//	unit	not set for	Axis1Powered
	//	standard_unit	not set for	Axis1Powered
	//	display_unit	not set for	Axis1Powered
	//	format	not set for	Axis1Powered
	//	max_value	not set for	Axis1Powered
	//	min_value	not set for	Axis1Powered
	//	max_alarm	not set for	Axis1Powered
	//	min_alarm	not set for	Axis1Powered
	//	max_warning	not set for	Axis1Powered
	//	min_warning	not set for	Axis1Powered
	//	delta_t	not set for	Axis1Powered
	//	delta_val	not set for	Axis1Powered
	axis1powered->set_default_properties(axis1powered_prop);
	//	Not Polled
	axis1powered->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1Powered does not fire change event
	//	Axis1Powered does not fire archive event
	//	Axis1Powered does not fire data_ready event
	att_list.push_back(axis1powered);

	//	Attribute : CS1Status
	CS1StatusAttrib	*cs1status = new CS1StatusAttrib();
	Tango::UserDefaultAttrProp	cs1status_prop;
	//	description	not set for	CS1Status
	//	label	not set for	CS1Status
	//	unit	not set for	CS1Status
	//	standard_unit	not set for	CS1Status
	//	display_unit	not set for	CS1Status
	//	format	not set for	CS1Status
	//	max_value	not set for	CS1Status
	//	min_value	not set for	CS1Status
	//	max_alarm	not set for	CS1Status
	//	min_alarm	not set for	CS1Status
	//	max_warning	not set for	CS1Status
	//	min_warning	not set for	CS1Status
	//	delta_t	not set for	CS1Status
	//	delta_val	not set for	CS1Status
	cs1status->set_default_properties(cs1status_prop);
	//	Not Polled
	cs1status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	CS1Status does not fire change event
	//	CS1Status does not fire archive event
	//	CS1Status does not fire data_ready event
	att_list.push_back(cs1status);

	//	Attribute : Axis1DeadBand
	Axis1DeadBandAttrib	*axis1deadband = new Axis1DeadBandAttrib();
	Tango::UserDefaultAttrProp	axis1deadband_prop;
	//	description	not set for	Axis1DeadBand
	//	label	not set for	Axis1DeadBand
	//	unit	not set for	Axis1DeadBand
	//	standard_unit	not set for	Axis1DeadBand
	//	display_unit	not set for	Axis1DeadBand
	//	format	not set for	Axis1DeadBand
	//	max_value	not set for	Axis1DeadBand
	//	min_value	not set for	Axis1DeadBand
	//	max_alarm	not set for	Axis1DeadBand
	//	min_alarm	not set for	Axis1DeadBand
	//	max_warning	not set for	Axis1DeadBand
	//	min_warning	not set for	Axis1DeadBand
	//	delta_t	not set for	Axis1DeadBand
	//	delta_val	not set for	Axis1DeadBand
	axis1deadband->set_default_properties(axis1deadband_prop);
	//	Not Polled
	axis1deadband->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1DeadBand does not fire change event
	//	Axis1DeadBand does not fire archive event
	//	Axis1DeadBand does not fire data_ready event
	att_list.push_back(axis1deadband);

	//	Attribute : Axis1Speed
	Axis1SpeedAttrib	*axis1speed = new Axis1SpeedAttrib();
	Tango::UserDefaultAttrProp	axis1speed_prop;
	//	description	not set for	Axis1Speed
	//	label	not set for	Axis1Speed
	//	unit	not set for	Axis1Speed
	//	standard_unit	not set for	Axis1Speed
	//	display_unit	not set for	Axis1Speed
	//	format	not set for	Axis1Speed
	//	max_value	not set for	Axis1Speed
	//	min_value	not set for	Axis1Speed
	//	max_alarm	not set for	Axis1Speed
	//	min_alarm	not set for	Axis1Speed
	//	max_warning	not set for	Axis1Speed
	//	min_warning	not set for	Axis1Speed
	//	delta_t	not set for	Axis1Speed
	//	delta_val	not set for	Axis1Speed
	axis1speed->set_default_properties(axis1speed_prop);
	//	Not Polled
	axis1speed->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1Speed does not fire change event
	//	Axis1Speed does not fire archive event
	//	Axis1Speed does not fire data_ready event
	att_list.push_back(axis1speed);

	//	Attribute : Axis1Acceleration
	Axis1AccelerationAttrib	*axis1acceleration = new Axis1AccelerationAttrib();
	Tango::UserDefaultAttrProp	axis1acceleration_prop;
	//	description	not set for	Axis1Acceleration
	//	label	not set for	Axis1Acceleration
	//	unit	not set for	Axis1Acceleration
	//	standard_unit	not set for	Axis1Acceleration
	//	display_unit	not set for	Axis1Acceleration
	//	format	not set for	Axis1Acceleration
	//	max_value	not set for	Axis1Acceleration
	//	min_value	not set for	Axis1Acceleration
	//	max_alarm	not set for	Axis1Acceleration
	//	min_alarm	not set for	Axis1Acceleration
	//	max_warning	not set for	Axis1Acceleration
	//	min_warning	not set for	Axis1Acceleration
	//	delta_t	not set for	Axis1Acceleration
	//	delta_val	not set for	Axis1Acceleration
	axis1acceleration->set_default_properties(axis1acceleration_prop);
	//	Not Polled
	axis1acceleration->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1Acceleration does not fire change event
	//	Axis1Acceleration does not fire archive event
	//	Axis1Acceleration does not fire data_ready event
	att_list.push_back(axis1acceleration);

	//	Attribute : Axes1to3Positions
	Axes1to3PositionsAttrib	*axes1to3positions = new Axes1to3PositionsAttrib();
	Tango::UserDefaultAttrProp	axes1to3positions_prop;
	//	description	not set for	Axes1to3Positions
	//	label	not set for	Axes1to3Positions
	//	unit	not set for	Axes1to3Positions
	//	standard_unit	not set for	Axes1to3Positions
	//	display_unit	not set for	Axes1to3Positions
	//	format	not set for	Axes1to3Positions
	//	max_value	not set for	Axes1to3Positions
	//	min_value	not set for	Axes1to3Positions
	//	max_alarm	not set for	Axes1to3Positions
	//	min_alarm	not set for	Axes1to3Positions
	//	max_warning	not set for	Axes1to3Positions
	//	min_warning	not set for	Axes1to3Positions
	//	delta_t	not set for	Axes1to3Positions
	//	delta_val	not set for	Axes1to3Positions
	axes1to3positions->set_default_properties(axes1to3positions_prop);
	//	Not Polled
	axes1to3positions->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axes1to3Positions does not fire change event
	//	Axes1to3Positions does not fire archive event
	//	Axes1to3Positions does not fire data_ready event
	att_list.push_back(axes1to3positions);

	//	Attribute : Motor1to3Status
	Motor1to3StatusAttrib	*motor1to3status = new Motor1to3StatusAttrib();
	Tango::UserDefaultAttrProp	motor1to3status_prop;
	//	description	not set for	Motor1to3Status
	//	label	not set for	Motor1to3Status
	//	unit	not set for	Motor1to3Status
	//	standard_unit	not set for	Motor1to3Status
	//	display_unit	not set for	Motor1to3Status
	//	format	not set for	Motor1to3Status
	//	max_value	not set for	Motor1to3Status
	//	min_value	not set for	Motor1to3Status
	//	max_alarm	not set for	Motor1to3Status
	//	min_alarm	not set for	Motor1to3Status
	//	max_warning	not set for	Motor1to3Status
	//	min_warning	not set for	Motor1to3Status
	//	delta_t	not set for	Motor1to3Status
	//	delta_val	not set for	Motor1to3Status
	motor1to3status->set_default_properties(motor1to3status_prop);
	//	Not Polled
	motor1to3status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Motor1to3Status does not fire change event
	//	Motor1to3Status does not fire archive event
	//	Motor1to3Status does not fire data_ready event
	att_list.push_back(motor1to3status);

	//	Attribute : CS1to3Status
	CS1to3StatusAttrib	*cs1to3status = new CS1to3StatusAttrib();
	Tango::UserDefaultAttrProp	cs1to3status_prop;
	//	description	not set for	CS1to3Status
	//	label	not set for	CS1to3Status
	//	unit	not set for	CS1to3Status
	//	standard_unit	not set for	CS1to3Status
	//	display_unit	not set for	CS1to3Status
	//	format	not set for	CS1to3Status
	//	max_value	not set for	CS1to3Status
	//	min_value	not set for	CS1to3Status
	//	max_alarm	not set for	CS1to3Status
	//	min_alarm	not set for	CS1to3Status
	//	max_warning	not set for	CS1to3Status
	//	min_warning	not set for	CS1to3Status
	//	delta_t	not set for	CS1to3Status
	//	delta_val	not set for	CS1to3Status
	cs1to3status->set_default_properties(cs1to3status_prop);
	//	Not Polled
	cs1to3status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	CS1to3Status does not fire change event
	//	CS1to3Status does not fire archive event
	//	CS1to3Status does not fire data_ready event
	att_list.push_back(cs1to3status);

	//	Attribute : Axes1to3Velocities
	Axes1to3VelocitiesAttrib	*axes1to3velocities = new Axes1to3VelocitiesAttrib();
	Tango::UserDefaultAttrProp	axes1to3velocities_prop;
	//	description	not set for	Axes1to3Velocities
	//	label	not set for	Axes1to3Velocities
	//	unit	not set for	Axes1to3Velocities
	//	standard_unit	not set for	Axes1to3Velocities
	//	display_unit	not set for	Axes1to3Velocities
	//	format	not set for	Axes1to3Velocities
	//	max_value	not set for	Axes1to3Velocities
	//	min_value	not set for	Axes1to3Velocities
	//	max_alarm	not set for	Axes1to3Velocities
	//	min_alarm	not set for	Axes1to3Velocities
	//	max_warning	not set for	Axes1to3Velocities
	//	min_warning	not set for	Axes1to3Velocities
	//	delta_t	not set for	Axes1to3Velocities
	//	delta_val	not set for	Axes1to3Velocities
	axes1to3velocities->set_default_properties(axes1to3velocities_prop);
	//	Not Polled
	axes1to3velocities->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axes1to3Velocities does not fire change event
	//	Axes1to3Velocities does not fire archive event
	//	Axes1to3Velocities does not fire data_ready event
	att_list.push_back(axes1to3velocities);

	//	Attribute : Axis1SoftwareLimits
	Axis1SoftwareLimitsAttrib	*axis1softwarelimits = new Axis1SoftwareLimitsAttrib();
	Tango::UserDefaultAttrProp	axis1softwarelimits_prop;
	//	description	not set for	Axis1SoftwareLimits
	//	label	not set for	Axis1SoftwareLimits
	//	unit	not set for	Axis1SoftwareLimits
	//	standard_unit	not set for	Axis1SoftwareLimits
	//	display_unit	not set for	Axis1SoftwareLimits
	//	format	not set for	Axis1SoftwareLimits
	//	max_value	not set for	Axis1SoftwareLimits
	//	min_value	not set for	Axis1SoftwareLimits
	//	max_alarm	not set for	Axis1SoftwareLimits
	//	min_alarm	not set for	Axis1SoftwareLimits
	//	max_warning	not set for	Axis1SoftwareLimits
	//	min_warning	not set for	Axis1SoftwareLimits
	//	delta_t	not set for	Axis1SoftwareLimits
	//	delta_val	not set for	Axis1SoftwareLimits
	axis1softwarelimits->set_default_properties(axis1softwarelimits_prop);
	//	Not Polled
	axis1softwarelimits->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Axis1SoftwareLimits does not fire change event
	//	Axis1SoftwareLimits does not fire archive event
	//	Axis1SoftwareLimits does not fire data_ready event
	att_list.push_back(axis1softwarelimits);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::attribute_factory_after

}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACAxes::PowerPMACAxesClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void PowerPMACAxesClass::command_factory()
{
	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::command_factory_before

	AxisHomeClass	*pAxisHomeCmd =
		new AxisHomeClass("AxisHome",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The number of the axis to home",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxisHomeCmd);
	AxisStopClass	*pAxisStopCmd =
		new AxisStopClass("AxisStop",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The number of the axis to stop",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxisStopCmd);
	AxisAbortClass	*pAxisAbortCmd =
		new AxisAbortClass("AxisAbort",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The number of the axis to abort",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxisAbortCmd);
	AxisMovePositiveClass	*pAxisMovePositiveCmd =
		new AxisMovePositiveClass("AxisMovePositive",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The number of the axis to move forward",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxisMovePositiveCmd);
	AxisMoveNegativeClass	*pAxisMoveNegativeCmd =
		new AxisMoveNegativeClass("AxisMoveNegative",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The number of the axis to move backward",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxisMoveNegativeCmd);
	Axis1MoveAbsClass	*pAxis1MoveAbsCmd =
		new Axis1MoveAbsClass("Axis1MoveAbs",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"The absolute position",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxis1MoveAbsCmd);
	Axis1MoveRelClass	*pAxis1MoveRelCmd =
		new Axis1MoveRelClass("Axis1MoveRel",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"The relative position",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxis1MoveRelCmd);
	Axis1DefinePositionClass	*pAxis1DefinePositionCmd =
		new Axis1DefinePositionClass("Axis1DefinePosition",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"New position",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAxis1DefinePositionCmd);

	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void PowerPMACAxesClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		PowerPMACAxesClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PowerPMACAxesClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PowerPMACAxes *dev = static_cast<PowerPMACAxes *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(PowerPMACAxes::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACAxes::Class::Additional Methods

} //	namespace
