/*----- PROTECTED REGION ID(PowerPMACBoxClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        PowerPMACBoxClass.cpp
//
// description : C++ source for the PowerPMACBoxClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     PowerPMACTangoDev.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PowerPMACBoxClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create PowerPMACBoxClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PowerPMACBox_class(const char *name) {
		return PowerPMACBox_ns::PowerPMACBoxClass::init(name);
	}
}


namespace PowerPMACBox_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PowerPMACBoxClass *PowerPMACBoxClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::PowerPMACBoxClass(string &s)
 * description : 	constructor for the PowerPMACBoxClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PowerPMACBoxClass::PowerPMACBoxClass(string &s):DeviceClass(s)
{
	cout2 << "Entering PowerPMACBoxClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PowerPMACBox::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::constructor

	cout2 << "Leaving PowerPMACBoxClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::~PowerPMACBoxClass()
 * description : 	destructor for the PowerPMACBoxClass
 */
//--------------------------------------------------------
PowerPMACBoxClass::~PowerPMACBoxClass()
{
	/*----- PROTECTED REGION ID(PowerPMACBox::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PowerPMACBoxClass *PowerPMACBoxClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PowerPMACBoxClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PowerPMACBoxClass *PowerPMACBoxClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ResetClass::execute(): arrived" << endl;

	
	((static_cast<PowerPMACBox *>(device))->reset());
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		DownloadClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *DownloadClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "DownloadClass::execute(): arrived" << endl;

	Tango::DevString	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->download(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		EnablePlcClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *EnablePlcClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "EnablePlcClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->enable_plc(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		DisablePlcClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *DisablePlcClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "DisablePlcClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->disable_plc(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		RunMprogClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *RunMprogClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "RunMprogClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->run_mprog(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AbortMprogClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AbortMprogClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AbortMprogClass::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->abort_mprog(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		GetVariableClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetVariableClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "GetVariableClass::execute(): arrived" << endl;

	Tango::DevString	argin;
	extract(in_any, argin);
	return insert((static_cast<PowerPMACBox *>(device))->get_variable(argin));
}
//--------------------------------------------------------
/**
 * method : 		SetVariableClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetVariableClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetVariableClass::execute(): arrived" << endl;

	const Tango::DevVarDoubleStringArray	*argin;
	extract(in_any, argin);
	((static_cast<PowerPMACBox *>(device))->set_variable(argin));
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		AbortClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AbortClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AbortClass::execute(): arrived" << endl;

	
	((static_cast<PowerPMACBox *>(device))->abort());
	return new CORBA::Any();
}




//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACBoxClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACBoxClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerPMACBoxClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void PowerPMACBoxClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void PowerPMACBoxClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties

	prop_name = "IpAddress";
	prop_desc = "IP address of the Power PMAC";
	prop_def  = "192.168.0.48\n";
	vect_data.clear();
	vect_data.push_back("192.168.0.48");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Username";
	prop_desc = "Username for Power PMAC SSH connection";
	prop_def  = "root\n";
	vect_data.clear();
	vect_data.push_back("root");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Password";
	prop_desc = "Password for Power PMAC SSH connection";
	prop_def  = "deltatau\n";
	vect_data.clear();
	vect_data.push_back("deltatau");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PowerPMACBoxClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("PowerPMACTangoDev");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("PowerPMACBox");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void PowerPMACBoxClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(PowerPMACBox::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PowerPMACBox(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PowerPMACBox *dev = static_cast<PowerPMACBox *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PowerPMACBox::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void PowerPMACBoxClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PowerPMACBox::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::attribute_factory_before


	//	Attribute : P1000
	P1000Attrib	*p1000 = new P1000Attrib();
	Tango::UserDefaultAttrProp	p1000_prop;
	//	description	not set for	P1000
	//	label	not set for	P1000
	//	unit	not set for	P1000
	//	standard_unit	not set for	P1000
	//	display_unit	not set for	P1000
	//	format	not set for	P1000
	//	max_value	not set for	P1000
	//	min_value	not set for	P1000
	//	max_alarm	not set for	P1000
	//	min_alarm	not set for	P1000
	//	max_warning	not set for	P1000
	//	min_warning	not set for	P1000
	//	delta_t	not set for	P1000
	//	delta_val	not set for	P1000
	p1000->set_default_properties(p1000_prop);
	//	Not Polled
	p1000->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	P1000 does not fire change event
	//	P1000 does not fire archive event
	//	P1000 does not fire data_ready event
	att_list.push_back(p1000);

	//	Attribute : GeneralStatus
	GeneralStatusAttrib	*generalstatus = new GeneralStatusAttrib();
	Tango::UserDefaultAttrProp	generalstatus_prop;
	//	description	not set for	GeneralStatus
	//	label	not set for	GeneralStatus
	//	unit	not set for	GeneralStatus
	//	standard_unit	not set for	GeneralStatus
	//	display_unit	not set for	GeneralStatus
	//	format	not set for	GeneralStatus
	//	max_value	not set for	GeneralStatus
	//	min_value	not set for	GeneralStatus
	//	max_alarm	not set for	GeneralStatus
	//	min_alarm	not set for	GeneralStatus
	//	max_warning	not set for	GeneralStatus
	//	min_warning	not set for	GeneralStatus
	//	delta_t	not set for	GeneralStatus
	//	delta_val	not set for	GeneralStatus
	generalstatus->set_default_properties(generalstatus_prop);
	//	Not Polled
	generalstatus->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	GeneralStatus does not fire change event
	//	GeneralStatus does not fire archive event
	//	GeneralStatus does not fire data_ready event
	att_list.push_back(generalstatus);

	//	Attribute : Version
	VersionAttrib	*version = new VersionAttrib();
	Tango::UserDefaultAttrProp	version_prop;
	//	description	not set for	Version
	//	label	not set for	Version
	//	unit	not set for	Version
	//	standard_unit	not set for	Version
	//	display_unit	not set for	Version
	//	format	not set for	Version
	//	max_value	not set for	Version
	//	min_value	not set for	Version
	//	max_alarm	not set for	Version
	//	min_alarm	not set for	Version
	//	max_warning	not set for	Version
	//	min_warning	not set for	Version
	//	delta_t	not set for	Version
	//	delta_val	not set for	Version
	version->set_default_properties(version_prop);
	//	Not Polled
	version->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Version does not fire change event
	//	Version does not fire archive event
	//	Version does not fire data_ready event
	att_list.push_back(version);

	//	Attribute : Plc8Status
	Plc8StatusAttrib	*plc8status = new Plc8StatusAttrib();
	Tango::UserDefaultAttrProp	plc8status_prop;
	//	description	not set for	Plc8Status
	//	label	not set for	Plc8Status
	//	unit	not set for	Plc8Status
	//	standard_unit	not set for	Plc8Status
	//	display_unit	not set for	Plc8Status
	//	format	not set for	Plc8Status
	//	max_value	not set for	Plc8Status
	//	min_value	not set for	Plc8Status
	//	max_alarm	not set for	Plc8Status
	//	min_alarm	not set for	Plc8Status
	//	max_warning	not set for	Plc8Status
	//	min_warning	not set for	Plc8Status
	//	delta_t	not set for	Plc8Status
	//	delta_val	not set for	Plc8Status
	plc8status->set_default_properties(plc8status_prop);
	//	Not Polled
	plc8status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Plc8Status does not fire change event
	//	Plc8Status does not fire archive event
	//	Plc8Status does not fire data_ready event
	att_list.push_back(plc8status);

	//	Attribute : CS1ProgStatus
	CS1ProgStatusAttrib	*cs1progstatus = new CS1ProgStatusAttrib();
	Tango::UserDefaultAttrProp	cs1progstatus_prop;
	//	description	not set for	CS1ProgStatus
	//	label	not set for	CS1ProgStatus
	//	unit	not set for	CS1ProgStatus
	//	standard_unit	not set for	CS1ProgStatus
	//	display_unit	not set for	CS1ProgStatus
	//	format	not set for	CS1ProgStatus
	//	max_value	not set for	CS1ProgStatus
	//	min_value	not set for	CS1ProgStatus
	//	max_alarm	not set for	CS1ProgStatus
	//	min_alarm	not set for	CS1ProgStatus
	//	max_warning	not set for	CS1ProgStatus
	//	min_warning	not set for	CS1ProgStatus
	//	delta_t	not set for	CS1ProgStatus
	//	delta_val	not set for	CS1ProgStatus
	cs1progstatus->set_default_properties(cs1progstatus_prop);
	//	Not Polled
	cs1progstatus->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	CS1ProgStatus does not fire change event
	//	CS1ProgStatus does not fire archive event
	//	CS1ProgStatus does not fire data_ready event
	att_list.push_back(cs1progstatus);

	//	Attribute : P1
	P1Attrib	*p1 = new P1Attrib();
	Tango::UserDefaultAttrProp	p1_prop;
	//	description	not set for	P1
	//	label	not set for	P1
	//	unit	not set for	P1
	//	standard_unit	not set for	P1
	//	display_unit	not set for	P1
	//	format	not set for	P1
	//	max_value	not set for	P1
	//	min_value	not set for	P1
	//	max_alarm	not set for	P1
	//	min_alarm	not set for	P1
	//	max_warning	not set for	P1
	//	min_warning	not set for	P1
	//	delta_t	not set for	P1
	//	delta_val	not set for	P1
	p1->set_default_properties(p1_prop);
	//	Not Polled
	p1->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	P1 does not fire change event
	//	P1 does not fire archive event
	//	P1 does not fire data_ready event
	att_list.push_back(p1);

	//	Attribute : Buffer
	BufferAttrib	*buffer = new BufferAttrib();
	Tango::UserDefaultAttrProp	buffer_prop;
	//	description	not set for	Buffer
	//	label	not set for	Buffer
	//	unit	not set for	Buffer
	//	standard_unit	not set for	Buffer
	//	display_unit	not set for	Buffer
	//	format	not set for	Buffer
	//	max_value	not set for	Buffer
	//	min_value	not set for	Buffer
	//	max_alarm	not set for	Buffer
	//	min_alarm	not set for	Buffer
	//	max_warning	not set for	Buffer
	//	min_warning	not set for	Buffer
	//	delta_t	not set for	Buffer
	//	delta_val	not set for	Buffer
	buffer->set_default_properties(buffer_prop);
	//	Not Polled
	buffer->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Buffer does not fire change event
	//	Buffer does not fire archive event
	//	Buffer does not fire data_ready event
	att_list.push_back(buffer);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(PowerPMACBox::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::attribute_factory_after

}


//--------------------------------------------------------
/**
 *	Method      : PowerPMACBox::PowerPMACBoxClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void PowerPMACBoxClass::command_factory()
{
	/*----- PROTECTED REGION ID(PowerPMACBox::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::command_factory_before

	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);
	DownloadClass	*pDownloadCmd =
		new DownloadClass("Download",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"filepath",
			"",
			Tango::OPERATOR);
	command_list.push_back(pDownloadCmd);
	EnablePlcClass	*pEnablePlcCmd =
		new EnablePlcClass("EnablePlc",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"PLC number",
			"",
			Tango::OPERATOR);
	command_list.push_back(pEnablePlcCmd);
	DisablePlcClass	*pDisablePlcCmd =
		new DisablePlcClass("DisablePlc",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"PLC number",
			"",
			Tango::OPERATOR);
	command_list.push_back(pDisablePlcCmd);
	RunMprogClass	*pRunMprogCmd =
		new RunMprogClass("RunMprog",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"Coordinate System number",
			"",
			Tango::OPERATOR);
	command_list.push_back(pRunMprogCmd);
	AbortMprogClass	*pAbortMprogCmd =
		new AbortMprogClass("AbortMprog",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"Coordinate system number",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAbortMprogCmd);
	GetVariableClass	*pGetVariableCmd =
		new GetVariableClass("GetVariable",
			Tango::DEV_STRING, Tango::DEV_FLOAT,
			"Variable Name",
			"Variable Value",
			Tango::OPERATOR);
	command_list.push_back(pGetVariableCmd);
	SetVariableClass	*pSetVariableCmd =
		new SetVariableClass("SetVariable",
			Tango::DEVVAR_DOUBLESTRINGARRAY, Tango::DEV_VOID,
			"A set of a string (Variable Name) and a double (new value)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetVariableCmd);
	AbortClass	*pAbortCmd =
		new AbortClass("Abort",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAbortCmd);

	/*----- PROTECTED REGION ID(PowerPMACBox::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void PowerPMACBoxClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(PowerPMACBox::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		PowerPMACBoxClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PowerPMACBoxClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PowerPMACBox *dev = static_cast<PowerPMACBox *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PowerPMACBox::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(PowerPMACBox::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	PowerPMACBox::Class::Additional Methods

} //	namespace
